title: AHMAD JARIF YEASIR
description: EEE Graduate @ IUT, Class of '22
baseurl: "/CV/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "ahmadjarif@iut-dhaka.edu"
linkedin: "https://www.linkedin.com/in/ahmadjarif"
github: "https://github.com/ahmad-jarif"
#website: "http://tahanima.github.io/"
#medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
